import type { Discovery, GeneratedProfile, Opportunity, PersonProfile } from "@/lib/types";

export const demoProfile: GeneratedProfile = {
  summary: "兼具工程实现与创意表达潜力的软件工程学习者，适合从 AI 应用和交互体验切入跨学科项目。",
  skills: [
    { name: "软件开发", score: 82, category: "技术", confidence: 86, evidence: ["C++ 课程项目", "Python 数据分析"] },
    { name: "游戏开发", score: 74, category: "创意", confidence: 79, evidence: ["EasyX 小游戏", "Unity 学习经历"] },
    { name: "数据分析", score: 66, category: "技术", confidence: 68, evidence: ["Python 数据分析"] },
    { name: "团队协作", score: 71, category: "协作", confidence: 55, evidence: ["项目协作描述较少，建议补充"] },
  ],
  interests: ["独立游戏", "人工智能", "开源社区", "视觉叙事"],
  potentialDirections: ["AI 应用开发", "游戏工具开发", "人机交互"],
  analysisMode: "rules",
  evidenceCount: 4,
};

export const matches: PersonProfile[] = [
  {
    id: "lin-yi",
    name: "林一",
    major: "视觉传达",
    grade: "大二",
    avatar: "林",
    match: 94,
    tags: ["UI 设计", "品牌视觉"],
    reason: "你的工程能力与她的视觉设计经验高度互补",
    status: "正在寻找校园产品项目",
    interestedOpportunityIds: ["ccdc-2026", "innovation-2026"],
    bio: "关注校园产品、品牌视觉和用户体验，希望与技术方向的同学共同完成可落地作品。",
    contact: "linyi_design（微信）",
    availability: "工作日晚间、周末",
    portfolio: "https://example.com/linyi",
    scoreBreakdown: { complementarity: 97, sharedInterests: 82, crossDiscipline: 96 },
  },
  {
    id: "zhou-yu",
    name: "周宇",
    major: "建筑学",
    grade: "大三",
    avatar: "周",
    match: 89,
    tags: ["数字建筑", "3D 建模"],
    reason: "游戏世界构建与空间设计存在有趣交叉",
    status: "想尝试虚拟校园项目",
    interestedOpportunityIds: ["innovation-2026", "challenge-cup"],
    bio: "对数字建筑、空间叙事和虚拟校园感兴趣，擅长调研、建模与方案表达。",
    contact: "zhouyu_space（微信）",
    availability: "周三、周五晚及周末",
    scoreBreakdown: { complementarity: 88, sharedInterests: 76, crossDiscipline: 100 },
  },
  {
    id: "chen-xi",
    name: "陈曦",
    major: "数字媒体",
    grade: "大二",
    avatar: "陈",
    match: 86,
    tags: ["Unity", "交互装置"],
    reason: "你们都对游戏与智能交互感兴趣",
    status: "本周可参与新项目",
    interestedOpportunityIds: ["ccdc-2026"],
    bio: "数字媒体方向，持续学习 Unity 与交互装置，希望参与游戏或智能交互类竞赛。",
    contact: "chenxi_media（微信）",
    availability: "本周起可稳定投入",
    portfolio: "https://example.com/chenxi",
    scoreBreakdown: { complementarity: 90, sharedInterests: 90, crossDiscipline: 78 },
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "ccdc-2026",
    title: "2026 中国大学生计算机设计大赛",
    organizer: "中国大学生计算机设计大赛组织委员会",
    type: "学术竞赛",
    status: "官方 2026 参赛要求已发布",
    deadline: "关注校赛与省赛通知",
    fit: 94,
    description: "设有软件应用与开发、人工智能应用、数媒游戏与交互设计等 11 个大类。",
    tags: ["软件开发", "人工智能", "交互设计"],
    sourceName: "中国大学生计算机设计大赛官网",
    sourceUrl: "https://jsjds.blcu.edu.cn/gyds1/csyq.htm",
    verifiedAt: "2026-08-20",
    bonusPolicy: "待导入所在学院 2026 年综测细则",
    accent: "violet",
    registrationStart: null,
    registrationEnd: null,
    eventDate: "2026-07-01",
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "innovation-2026",
    title: "中国国际大学生创新大赛（2026）",
    organizer: "教育部等部门与地方政府",
    type: "创新创业",
    status: "官方 2026 服务入口已上线",
    deadline: "以学校报名通知为准",
    fit: 89,
    description: "面向高等教育不同赛道的创新创业赛事，需通过学校组织报名。",
    tags: ["创新创业", "产品实践", "跨专业"],
    sourceName: "全国大学生创业服务网",
    sourceUrl: "https://cy.ncss.cn/provincecontact",
    verifiedAt: "2026-08-20",
    bonusPolicy: "待导入学校及学院当年认定规则",
    accent: "cyan",
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "challenge-cup",
    title: "“挑战杯”全国大学生系列科技学术竞赛",
    organizer: "共青团中央、中国科协、教育部等",
    type: "创新创业",
    status: "官方长期赛事入口",
    deadline: "关注当届校赛通知",
    fit: 84,
    description: "包含课外学术科技作品竞赛和创业计划竞赛，两项赛事交叉轮流开展。",
    tags: ["科技创新", "社会调研", "创业计划"],
    sourceName: "挑战杯官方网站",
    sourceUrl: "https://tiaozhanbei.net/",
    verifiedAt: "2026-08-20",
    bonusPolicy: "待导入所在学院当年综测与保研认定文件",
    accent: "amber",
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "cumcm-2026",
    title: "2026 高教社杯全国大学生数学建模竞赛",
    organizer: "中国工业与应用数学学会全国大学生数学建模竞赛组委会",
    type: "学术竞赛",
    status: "官方 2026 竞赛安排已发布",
    deadline: "2026-09-07 20:00 报名截止",
    fit: 88,
    description: "三人组队，在限定时间内围绕工程、管理或社会问题完成模型建立、计算分析与论文写作。",
    tags: ["数学建模", "数据分析", "编程", "论文写作"],
    sourceName: "全国大学生数学建模竞赛官网",
    sourceUrl: "https://www.mcm.edu.cn/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院 2026 年竞赛认定规则为准",
    accent: "cyan",
    registrationStart: "2026-05-01",
    registrationEnd: "2026-09-07",
    eventDate: "2026-09-10",
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "nuedc-2026",
    title: "2026 全国大学生电子设计竞赛专题竞赛",
    organizer: "全国大学生电子设计竞赛组织委员会",
    type: "学术竞赛",
    status: "官方 2026 专题竞赛通知已发布",
    deadline: "不同专题赛时间不同，以官方通知和校内选拔为准",
    fit: 87,
    description: "覆盖嵌入式 AI、模拟电子系统和信息科技前沿等专题，强调电子系统设计、制作、调试与团队协作。",
    tags: ["电子设计", "嵌入式", "硬件调试", "人工智能"],
    sourceName: "全国大学生电子设计竞赛官网",
    sourceUrl: "https://nuedc.xjtu.edu.cn/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院 2026 年竞赛认定规则为准",
    accent: "violet",
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "c4-network-2026",
    title: "2026 中国高校计算机大赛—网络技术挑战赛",
    organizer: "中国高校计算机大赛网络技术挑战赛组委会",
    type: "学术竞赛",
    status: "官方 2026 赛程与决赛安排已发布",
    deadline: "本届选拔赛已结束，可关注下一届通知并提前组队",
    fit: 91,
    description: "面向网络技术研究、设计开发、应用管理及产学融合课题，适合软件、网络、物联网和安全方向跨专业组队。",
    tags: ["网络技术", "软件开发", "信息安全", "物联网"],
    sourceName: "中国高校计算机大赛网络技术挑战赛官网",
    sourceUrl: "https://net.c4best.cn/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院当年竞赛认定规则为准",
    accent: "cyan",
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "service-outsourcing-2026",
    title: "第十七届中国大学生服务外包创新创业大赛",
    organizer: "中国大学生服务外包创新创业大赛组委会",
    type: "创新创业",
    status: "2026 全国赛已结束，官方赛题与结果可查",
    deadline: "本届报名已结束，可使用官方赛题准备下一届",
    fit: 90,
    description: "包含企业命题、创业实践、OPC 创客和人工智能专项，强调真实产业问题、产品交付与创新创业能力。",
    tags: ["企业命题", "产品实践", "软件开发", "人工智能", "创新创业"],
    sourceName: "中国大学生服务外包创新创业大赛官网",
    sourceUrl: "https://www.fwwb.org.cn/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院当年竞赛认定规则为准",
    accent: "amber",
    registrationStart: "2026-02-11",
    registrationEnd: "2026-03-31",
    eventDate: "2026-08-24",
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "umic-2026",
    title: "第十二届全国大学生机械创新设计大赛",
    organizer: "全国大学生机械创新设计大赛组委会",
    type: "学术竞赛",
    status: "2026 常规赛全国决赛结果已发布",
    deadline: "本届已结束，可参考作品展播和赛题提前准备",
    fit: 80,
    description: "以机械创新设计和工程实现为核心，要求团队完成需求分析、机构设计、加工制作、控制调试与现场展示。",
    tags: ["机械设计", "结构设计", "智能制造", "控制"],
    sourceName: "全国大学生机械创新设计大赛官网",
    sourceUrl: "https://umic.moocollege.com/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院当年竞赛认定规则为准",
    accent: "amber",
    registrationStart: null,
    registrationEnd: null,
    eventDate: "2026-07-20",
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "smart-car-2026",
    title: "第二十一届全国大学生智能汽车竞赛",
    organizer: "中国自动化学会",
    type: "学术竞赛",
    status: "2026 竞赛通知和技术规范陆续发布",
    deadline: "按校内选拔、赛区与专项通知报名",
    fit: 86,
    description: "以智能车为工程载体，综合考察感知、控制、嵌入式开发、机械结构、电路设计和现场调试。",
    tags: ["自动控制", "嵌入式", "计算机视觉", "机械电子"],
    sourceName: "全国大学生智能汽车竞赛官网",
    sourceUrl: "https://www.smartcar.zone/",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院当年竞赛认定规则为准",
    accent: "violet",
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
  {
    id: "sun-ada-2026",
    title: "第十八届全国大学生广告艺术大赛",
    organizer: "全国大学生广告艺术大赛组委会",
    type: "文艺比赛",
    status: "2026 参赛指南与作品类别已发布",
    deadline: "本届线上提交已结束，可关注命题与下一届通知",
    fit: 82,
    description: "涵盖平面、视频、动画、互动、策划、文案、UI、生成式 AI 设计和营销创客等类别，适合创意与技术方向协作。",
    tags: ["视觉设计", "品牌策划", "交互设计", "AIGC", "视频"],
    sourceName: "全国大学生广告艺术大赛官网",
    sourceUrl: "https://www.sun-ada.net/about_intrs2.html",
    verifiedAt: "2026-08-29",
    bonusPolicy: "以学校及学院当年竞赛认定规则为准",
    accent: "cyan",
    registrationStart: "2026-05-10",
    registrationEnd: "2026-06-12",
    eventDate: "2026-07-05",
    scope: "全国",
    verification: "official",
    publisherId: null,
    publisherName: "DUT Link 赛事编辑",
  },
];

export const discoveries: Discovery[] = [
  {
    id: "architecture-software",
    eyebrow: "今日知识盲盒",
    title: "为什么程序员应该了解建筑学？",
    description: "从模块、动线与尺度出发，看看软件架构和真实空间如何用相似的方法组织复杂性。",
    bridge: "软件架构 × 空间设计",
    readTime: "6 分钟",
    why: "你有软件开发经历，而建筑学同样关心模块、边界、动线和人的行为。",
    generationMode: "curated",
    sources: [
      { title: "A Pattern Language — Christopher Alexander", url: "https://www.patternlanguage.com/", type: "文章" },
      { title: "Notes on the Synthesis of Form", url: "https://monoskop.org/images/f/ff/Alexander_Christopher_Notes_on_the_Synthesis_of_Form.pdf", type: "论文" },
    ],
  },
  {
    id: "game-campus-guide",
    eyebrow: "跨领域灵感",
    title: "用游戏设计重新想象校园导览",
    description: "任务、反馈与叙事不仅属于游戏，也能让新生探索校园的过程更自然。",
    bridge: "游戏机制 × 校园服务",
    readTime: "4 分钟",
    why: "游戏设计中的目标、反馈和探索机制，可以降低新生了解校园的认知成本。",
    generationMode: "curated",
    sources: [
      { title: "MDA: A Formal Approach to Game Design", url: "https://users.cs.northwestern.edu/~hunicke/MDA.pdf", type: "论文" },
    ],
  },
  {
    id: "music-debugging",
    eyebrow: "随机跨域",
    title: "调试代码和排练音乐有什么共同点？",
    description: "两者都需要把整体表现拆成可验证的小段，通过反馈循环定位偏差。",
    bridge: "软件调试 × 音乐排练",
    readTime: "5 分钟",
    why: "你关注工程实践，而音乐排练提供了另一套处理复杂系统与即时反馈的方法。",
    generationMode: "curated",
    sources: [
      { title: "The Cambridge Handbook of Expertise and Expert Performance", url: "https://doi.org/10.1017/CBO9780511816796", type: "论文" },
    ],
  },
];
